version: "3.4"
services:
  besu:
    image: suburbandad/besu:merge-interop
    restart: always
    container_name: besu
    volumes:
      - ./execution_data:/execution_data
      - ./$TESTNET_NAME/custom_config_data:/custom_config_data
    #ports:
    #  - "30303:30303" # P2P port
    #  - "8545:8545" # REST API port
    #  - "8546:8546" # WS API port
    command: >
      --data-path="/execution_data" 
      --genesis-file="/custom_config_data/besu_genesis.json" 
      --network-id=1337202 
      --rpc-http-enabled=true 
      --rpc-ws-enabled=true 
      --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION 
      --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --host-allowlist="*" 
      --rpc-http-cors-origins="*" 
      --p2p-enabled=true 
      --Xmerge-support=true 
      --miner-enabled=true 
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=${IP_ADDRESS} 
      --bootnodes=${BOOT_NODES}
      --miner-coinbase="0xFE3B557E8Fb62b89F4916B721be55cEb828dBd73" 

    network_mode: host






