- name: Backup data
  hosts: all
  gather_facts: false
  tasks:
    - name: Archive data dir to prepare for download
      archive:
        path: "{{ beacon_node_dir }}/*"
        dest: "{{ beacon_node_dir }}.tar.gz"
    - name: Creates beacon dir
      file:
        path: "/Users/parithosh/dev/eth2/amphora-testnet-playbooks/backups/{{ inventory_hostname }}/beacon"
        state: directory
      delegate_to: localhost
    - name: Copying the remote file
      ansible.posix.synchronize:
        use_ssh_args: true
        mode: pull
        src: "{{ beacon_node_dir }}.tar.gz"
        dest: "/Users/parithosh/dev/eth2/amphora-testnet-playbooks/backups/{{ inventory_hostname }}/beacon"
    - name: Archive data dir to prepare for download
      become: true
      archive:
        path: "{{ eth1_node_dir }}/*"
        dest: "{{ eth1_node_dir }}.tar.gz"
    - name: Creates beacon dir
      file:
        path: "/Users/parithosh/dev/eth2/amphora-testnet-playbooks/backups/{{ inventory_hostname }}/eth1node"
        state: directory
      delegate_to: localhost
    - name: Copying the remote file
      ansible.posix.synchronize:
        use_ssh_args: true
        mode: pull
        src: "{{ eth1_node_dir }}.tar.gz"
        dest: "/Users/parithosh/dev/eth2/amphora-testnet-playbooks/backups/{{ inventory_hostname }}/eth1node"
