eth1_client_name: nethermind
eth1_image_name: swaraj18/themerge-m3

eth1_memory: 5000M
eth1_kernel_memory: 5500M

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"

eth1_start_args: >
  --config networkdata

eth1_user_id: "1000:1000"
